image: ruby:2.7.2

cache:
  paths:
    - vendor/bundle
    - node_modules

variables:
  BUNDLE_PATH: vendor/bundle
  DISABLE_SPRING: 1
  NODE_VERSION: 12

stages:
  - test
  - quality
  - audit

rspec:
  stage: test
  before_script:
    # Install node
    - curl -sL https://deb.nodesource.com/setup_$NODE_VERSION.x | bash -
    - apt-get update -yq
    - apt-get install -y --no-install-recommends nodejs

    # Install yarn
    - wget -q -O - https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    - echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list
    - apt-get update -yq
    - apt-get install -y yarn
  script:
    - bin/setup
    - bundle exec rspec

rubocop:
  stage: quality
  script: bundle exec rubocop

audit:
  stage: audit
  allow_failure: true
  script:
    - gem install bundler-audit
    - bundle-audit check --update
