version: '3'
services:
  rails:
    build: .
    command: rails s -b 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - .:/promo
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - promo-data:/var/lib/postgresql/data
volumes:
  promo-data: